components:
- components:
  - layout_properties: {grid_position: 'SFBRCQ,VUFSNC'}
    name: heading
    properties: {align: center, role: headline, text: <Setup> your embedding}
    type: Label
  - layout_properties: {grid_position: 'GEYNWN,PXIXLP'}
    name: label_4
    properties: {text: Full Name}
    type: Label
  - layout_properties: {grid_position: 'GEYNWN,BHSONV'}
    name: txt_name
    properties: {}
    type: TextBox
  - layout_properties: {grid_position: 'PUXIPO,EXNBOA'}
    name: label_1_copy_copy
    properties: {text: Race}
    type: Label
  - layout_properties: {grid_position: 'PUXIPO,UIZRJI'}
    name: drp_races
    properties:
      items: []
    type: DropDown
  - layout_properties: {grid_position: 'XRNJQJ,QDPMLW'}
    name: label_5
    properties: {text: Bib Number}
    type: Label
  - layout_properties: {grid_position: 'XRNJQJ,ZXFAHD'}
    name: txt_bib
    properties: {}
    type: TextBox
  - layout_properties: {grid_position: 'ZNRMHO,IVAZAT'}
    name: label_1
    properties: {text: Email Address}
    type: Label
  - layout_properties: {grid_position: 'ZNRMHO,TNCHKK'}
    name: txt_email
    properties: {}
    type: TextBox
  - layout_properties: {grid_position: 'WDMWQK,TVSICI'}
    name: label_1_copy
    properties: {text: Activity App}
    type: Label
  - event_bindings: {change: drp_activity_app_change}
    layout_properties: {grid_position: 'WDMWQK,SNNXFB'}
    name: drp_activity_app
    properties:
      items: [None, Garmin, Strava]
    type: DropDown
  - layout_properties: {grid_position: 'AZJYIM,VKRZYF'}
    name: lbl_activity_info
    properties: {text: Activity Info, visible: false}
    type: Label
  - layout_properties: {grid_position: 'AZJYIM,WPCIRS'}
    name: txt_activity_info
    properties: {visible: false}
    type: TextArea
  - layout_properties: {grid_position: 'XDLXZE,AMFNFY'}
    name: lbl_instructions
    properties: {text: 'How do I find my <activity app> activity info?'}
    type: Link
  - data_bindings: []
    event_bindings: {click: btn_finish_click}
    layout_properties: {grid_position: 'YJVJRK,JZCASL'}
    name: btn_finish
    properties: {background: 'theme:Primary 500', foreground: 'theme:Gray 50', text: Finish}
    type: Button
  layout_properties: {slot: default}
  name: content_panel
  properties: {col_widths: '{"IVAZAT":10,"TNCHKK":50,"TVSICI":10,"SNNXFB":50,"VKRZYF":10,"WPCIRS":50,"PXIXLP":10,"BHSONV":50,"QDPMLW":10,"ZXFAHD":50,"EXNBOA":10,"UIZRJI":50}'}
  type: ColumnPanel
- layout_properties: {slot: nav-right}
  name: navbar_links
  properties: {}
  type: FlowPanel
container:
  properties: {html: '@theme:standard-page.html'}
  type: HtmlTemplate
